import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
//import { ApolloWrapper } from "/@lib/apollo-wrapper";

const openSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        {/* <ApolloWrapper>{children}</ApolloWrapper> */}
        {children}
      </body>
    </html>
  );
}
